# Generated by Django 5.0.6 on 2024-07-08 19:38

import core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Band name')),
                ('genre', models.CharField(choices=[('HM', 'Heavy Metal'), ('TM', 'Thrash Metal'), ('HR', 'Hard Rock'), ('PM', 'Power Metal'), ('DM', 'Death Metal')], default='HM', max_length=2, verbose_name='Band genre')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Band biography')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='band/<function upload_image at 0x791b515f1870>', validators=[core.validators.ValidateImageFileExtensionAndMineType()], verbose_name='Cover image')),
                ('created_at', models.DateField(blank=True, null=True, verbose_name='Year the band was founded')),
            ],
            options={
                'verbose_name_plural': 'Bands',
                'db_table': 'Bands',
                'ordering': ['genre', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='Album name')),
                ('release_date', models.DateField(blank=True, max_length=30, null=True, verbose_name='Release date')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='album/<function upload_image at 0x791b515f1870>', validators=[core.validators.ValidateImageFileExtensionAndMineType()], verbose_name='Cover image')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', related_query_name='album', to='core.band')),
            ],
            options={
                'ordering': ['band', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30, verbose_name='First name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last name')),
                ('date_birth', models.DateField(blank=True, help_text='Exemplo: (2024-05-30)', null=True, verbose_name='Date of birth')),
                ('type_musician', models.CharField(blank=True, choices=[('V', 'Vocal'), ('G', 'Guitar'), ('B', 'Bass'), ('D', 'Drummer'), ('VG', 'Vocal and Guitar'), ('VB', 'Vocal and Bass')], max_length=2, null=True, verbose_name='Type of musician / Instrument')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='musician/<function upload_image at 0x791b515f1870>', validators=[core.validators.ValidateImageFileExtensionAndMineType()], verbose_name='Cover image')),
                ('band', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='musicians', related_query_name='musician', to='core.band')),
            ],
            options={
                'ordering': ['band', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Track')),
                ('track_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='track number in the song list')),
                ('duration', models.CharField(blank=True, max_length=5, null=True, verbose_name='Song length')),
                ('letter', models.TextField(blank=True, null=True, verbose_name='Letter')),
                ('single', models.BooleanField(default=False, verbose_name='Single')),
                ('title_track', models.BooleanField(default=False, verbose_name='Song title track')),
                ('release_date', models.DateField(blank=True, max_length=30, null=True, verbose_name='Release date')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tracks', related_query_name='track', to='core.album')),
                ('by_composers', models.ManyToManyField(blank=True, related_name='tracks', related_query_name='track', to='core.musician')),
            ],
            options={
                'ordering': ['album', 'title'],
            },
        ),
    ]
