# Generated by Django 5.0.6 on 2024-07-08 19:39

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='album/<function upload_image at 0x71fe7ae85ab0>', validators=[core.validators.ValidateImageFileExtensionAndMineType()], verbose_name='Cover image'),
        ),
        migrations.AlterField(
            model_name='band',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='band/<function upload_image at 0x71fe7ae85ab0>', validators=[core.validators.ValidateImageFileExtensionAndMineType()], verbose_name='Cover image'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='musician/<function upload_image at 0x71fe7ae85ab0>', validators=[core.validators.ValidateImageFileExtensionAndMineType()], verbose_name='Cover image'),
        ),
    ]
