@hostname = http://127.0.0.1:8000

## ADMIN
GET {{hostname}}/api-admin/musicians
Authorization: Basic admin:password

## USERS
GET {{hostname}}/shaplayer/musicians-list
Authorization: Basic user:password

GET {{hostname}}/shaplayer/single-musician/1
Authorization: Basic user:password