@hostname = http://127.0.0.1:8000

## ADMIN
GET {{hostname}}/api-admin/tracks
Authorization: Basic admin:password

# ## USERS
GET {{hostname}}/shaplayer/tracks-list
Authorization: Basic user:password

GET {{hostname}}/shaplayer/single-track/1
Authorization: Basic user:password

# Filtering music tracks by band.
GET {{hostname}}/shaplayer/tracks-list/?band=iron maiden
Authorization: Basic user:password